"use server";

import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

// Check if user is staff
async function checkStaff() {
  const session = await auth();
  if (session?.user?.role !== "staff") {
    throw new Error("Unauthorized");
  }
  return session;
}

import { createGithubTeam, addMemberToTeam } from "@/lib/github-admin";

export async function joinCohort(token: string) {
  const session = await auth();
  if (!session?.user?.id) redirect("/");

  const cohort = await prisma.cohort.findUnique({
    where: { inviteToken: token, active: true },
  });

  if (!cohort) redirect("/"); // Should show error but for now redirect

  // Update User
  await prisma.user.update({
    where: { id: session.user.id },
    data: { cohortId: cohort.id },
  });

  // Add to GitHub Team
  // casting session.user as any to access custom fields if TS complains, mostly it should match extended type if configured properly
  // but in actions file, if next-auth types aren't global, it might be an issue.
  // Let's assume session.user includes githubUsername based on auth.ts profile callback.
  const username = (session.user as any).githubUsername;

  if (username && cohort.githubTeamSlug) {
    await addMemberToTeam(cohort.githubTeamSlug, username);
  }

  revalidatePath("/onboarding");
  redirect("/onboarding");
}

export async function createCohort(formData: FormData) {
  await checkStaff();

  const name = formData.get("name") as string;
  // We still accept slug if provided manually, but we prioritize creating the team
  let githubTeamSlug = formData.get("githubTeamSlug") as string;
  const awsAcademyLink = formData.get("awsAcademyLink") as string;

  if (!name || !awsAcademyLink) {
    redirect("/admin/cohorts/new?error=missing_fields");
  }

  // Attempt to create GitHub Team automatically
  const teamRes = await createGithubTeam(name);

  if (teamRes.error) {
    // If it failed (and wasn't just skipped like in dev mode without token), we should probably let the user know.
    // However, if we redirect, we lose the form state.
    // Ideally we should throw error or return it if we used useActionState.
    // Since we use simple form action, redirecting with error query param is the way.
    console.error("GitHub Team Creation Failed:", teamRes.error);
    return redirect(
      `/admin/cohorts/new?error=${encodeURIComponent(teamRes.error)}`,
    );
  }

  if (teamRes.success && teamRes.slug) {
    githubTeamSlug = teamRes.slug;
  } else if (!githubTeamSlug) {
    // Fallback (e.g. if skipped)
    githubTeamSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  }

  await prisma.cohort.create({
    data: {
      name,
      githubTeamSlug,
      awsAcademyLink,
      active: true,
      // inviteToken is auto-generated by DB
    },
  });

  revalidatePath("/admin/cohorts");
  redirect("/admin/cohorts");
}

export async function toggleCohortStatus(id: string, currentStatus: boolean) {
  await checkStaff();

  await prisma.cohort.update({
    where: { id },
    data: { active: !currentStatus },
  });

  revalidatePath("/admin/cohorts");
  return { success: true };
}

export async function assignStudentToCohort(userId: string, cohortId: string) {
  await checkStaff();

  await prisma.user.update({
    where: { id: userId },
    data: { cohortId },
  });

  revalidatePath("/admin");
  return { success: true };
}

export async function syncCohortTeam(cohortId: string) {
  await checkStaff();

  const cohort = await prisma.cohort.findUnique({ where: { id: cohortId } });
  if (!cohort) return { error: "Cohort not found" };

  // Try to create/get team
  const res = await createGithubTeam(cohort.name);

  if (res.error) {
    return { error: res.error };
  }

  if (res.slug && res.slug !== cohort.githubTeamSlug) {
    // Update slug if it changed (e.g. if we had a manual one but now got a real one, or it matches)
    await prisma.cohort.update({
      where: { id: cohortId },
      data: { githubTeamSlug: res.slug },
    });
  }

  revalidatePath("/admin/cohorts");
  return { success: true, slug: res.slug };
}
